Perpendicular line calculator added
sairish2001/makesmatheasy pull request #1205
Opened 2021-04-18 16:01 UTC by RaveenaBhasin

## Related Issue #1162 
I have added a calculator for checking whether two lines are perpendicular to each other or not.
![Screenshot (1835)](https://user-images.githubusercontent.com/73697080/115152119-7513d900-a08d-11eb-85c7-f4dbfb253509.png)

2021-04-18 19:34 UTC, sairish2001 approved these changes

2021-04-19 03:18 UTC, RaveenaBhasin commented
@sairish2001 Conflicts are resolved now.

2021-04-19 07:27 UTC, sairish2001 requested changes
change latex text back to white

2021-04-19 07:58 UTC, RaveenaBhasin commented
Done @sairish2001

2021-04-21 05:09 UTC, sairish2001 approved these changes

2021-04-21 05:10 UTC, merged