Added steps for leap year checker
sairish2001/makesmatheasy pull request #2387
Opened 2021-05-12 15:21 UTC by madihamallick

fix #1756 

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

![1](https://user-images.githubusercontent.com/70858557/118000738-b5503980-b363-11eb-9a94-041b419f9c21.PNG)
![2](https://user-images.githubusercontent.com/70858557/118000752-b7b29380-b363-11eb-8509-1c9c2a993c01.PNG)
![3](https://user-images.githubusercontent.com/70858557/118000753-b84b2a00-b363-11eb-93aa-effdc33bf24e.PNG)
![4](https://user-images.githubusercontent.com/70858557/118000758-b8e3c080-b363-11eb-87c9-c24c09064ba6.PNG)

2021-05-12 19:50 UTC, sairish2001 approved these changes

2021-05-12 19:52 UTC, sairish2001 requested changes
Instead of creating multiple ` <p> `tags, just concatenate a single string and then at last just insert into to` <p>` tag.

2021-05-12 19:55 UTC, madihamallick commented
> Instead of creating multiple `<p>`tags, just concatenate a single string and then at last just insert into to` <p>` tag.

Okay, will make the changes

2021-05-13 06:17 UTC, madihamallick commented
@sairish2001 I have created a new PR for this, #2429 
So, I'm closing this.

2021-05-13 06:17 UTC, closed without merging