fixed factors
sairish2001/makesmatheasy pull request #333
Opened 2021-03-22 07:14 UTC by keshavgbpecdelhi

## Related Issuse

- Issue #223

Closes: #223

#### Describe the changes you've made

The changes are as follows : 
- Modified the function Factors to show all the factors of a given number(s) which was initially showing prime factors which was basically the same code written for HCF finding also.
- Modified the README.md with  the functionality of the code and  for LCM and HCF also.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

#### So, Initially "Factors" does the same thing as the HCF "prime factors" does there was no new functionality and not all factors were shown in that. Just like the below Screenshot (here factors and hcf, shows the same result of prime factors only) 
![Screenshot (105)](https://user-images.githubusercontent.com/56075233/111952191-c4a4ca80-8b0a-11eb-846c-663b7a9b7862.png)

### Here is the modifications : 
#### For single input all factors will be shown like the screenshot below :
![Screenshot (102)](https://user-images.githubusercontent.com/56075233/111952301-ec942e00-8b0a-11eb-85bc-e520cdb05489.png)
#### For multiple inputs all factors of individual input will be shown like this screenshot below :
![Screenshot (104)](https://user-images.githubusercontent.com/56075233/111952280-e2722f80-8b0a-11eb-9b45-6ec29503ae94.png)

2021-03-22 07:56 UTC, sairish2001 requested changes
It seems you changed the functionality of Factors button
Don't remove the previous logic for Factors as it is Calculating Prime Factors

Just change Text of factors button to Prime Factors

and

add a new button named factors which will calculate factors with your logic

2021-03-22 07:59 UTC, keshavgbpecdelhi commented
> It seems you changed the functionality of Factors button
> Don't remove the previous logic for Factors as it is Calculating Prime Factors
> 
> Just change Text of factors button to Prime Factors
> 
> and
> 
> add a new button named factors which will calculate factors with your logic

Factor previously does the same thing which was done by it in hcf so the same code was written twice initially so I think there should not be another factor button but If its not a good idea i will change it.

2021-03-22 08:12 UTC, keshavgbpecdelhi commented
Can you help, how to create new tag and add functionality to it?

2021-03-22 08:43 UTC, sairish2001 commented
No no, just create another button, which onclick calls another function

2021-03-23 06:07 UTC, keshavgbpecdelhi commented
Unable to find the code written for these tags :/
![Screenshot (105)](https://user-images.githubusercontent.com/56075233/112101034-077aa700-8bcc-11eb-9bc5-82d3a1f50f57.png)

2021-03-23 17:22 UTC, khareyash05 commented
Hey @sairish2001 Should I work on this one?

2021-03-23 17:41 UTC, keshavgbpecdelhi commented
If I could get help 🥺

2021-03-23 17:47 UTC, khareyash05 commented
@keshavgbpecdelhi Ya thats what i stated as to help you 
@sairish2001 Can this be a collaborative issue?

2021-03-23 17:56 UTC, khareyash05 commented
@keshavgbpecdelhi first of all update your repo it isn't updated

2021-03-23 18:55 UTC, sairish2001 commented
> @keshavgbpecdelhi Ya thats what i stated as to help you
> @sairish2001 Can this be a collaborative issue?

No this can't be collaborative issue

2021-03-23 18:59 UTC, sairish2001 commented
@keshavgbpecdelhi 
refer to [appjs/logicjavascript.js](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/appjs/logicjavascript.js)

[start](https://github.com/sairish2001/makesmatheasy.github.io/blob/b1e666d69bd7b58ae345751e7103297410689fef/appjs/logicjavascript.js#L389

But actually there's no need to change anything in these functions.
Just create new `function___(){  }` and a new Button in `index.html` then apply onclick to this button

2021-03-25 09:39 UTC, khareyash05 commented
@keshavgbpecdelhi Update ur forked repo 
use 
```
git checkout main
git fetch upstream(first add git remote add upstream <then this repo's link>
git merge upstream/main
git push origin main
```
This will make merge conflicts go away

2021-03-25 09:44 UTC, keshavgbpecdelhi commented
Didn't understood what to do, first and then what! => git fetch upstream(first add git remote add upstream <then this repo's link>
I have to write this as it is? => git merge upstream/main

2021-03-25 10:18 UTC, khareyash05 commented
First of all add upstream using 
``` git remote add upstream https://github.com/sairish2001/MakesMathEasy.git ```
Then do this
```
git checkout main
git fetch upstream
git merge upstream/main
git push origin main
```

2021-03-25 12:05 UTC, keshavgbpecdelhi commented
This error I got after following the above steps :  

`$ git push origin main
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/keshavgbpecdelhi/MakesMathEasy.git
 ! [remote rejected] main -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/issue-labeler.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/keshavgbpecdelhi/MakesMathEasy.git'`


@khareyash05 pls look into this 🙏🏻

2021-03-25 14:18 UTC, khareyash05 commented
@keshavgbpecdelhi I am sorry mate I dont know why this error is coming up

2021-03-26 05:16 UTC, keshavgbpecdelhi commented
@sairish2001 I have done the required changes [@here](https://github.com/sairish2001/MakesMathEasy/pull/333/commits/ad3714badcbac81c29a342f6cdf1010a887327f5) 

If there is a need of anything or if I have to resolve the conflict, please look into this.
Thankyou 🙏🏻

2021-04-26 09:48 UTC, shonali2600 commented
@keshavgbpecdelhi, go through this https://jessehouwing.net/cannot-push-to-github-without-workflow-scope/, this may help you.

2021-04-29 07:36 UTC, keshavgbpecdelhi commented
@shonali2600 I read the article, I think this is not related with the current issue we are facing here. Here we are having merge conflicts. If you have something related with that, it would be highly appreciated.
Thanks

2021-04-29 19:06 UTC, keshavgbpecdelhi commented
Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$ git status
On branch main
Your branch is ahead of 'origin/main' by 100 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$ git remote -v
origin  https://github.com/keshavgbpecdelhi/MakesMathEasy.git (fetch)
origin  https://github.com/keshavgbpecdelhi/MakesMathEasy.git (push)
upstream        https://github.com/sairish2001/MakesMathEasy.git (fetch)
upstream        https://github.com/sairish2001/MakesMathEasy.git (push)

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$ git branch -a
  factors
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/factors
  remotes/origin/main
  remotes/origin/revert-170-revert-166-issue_93_back
  remotes/upstream/main

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$ git fetch upstream main
remote: Enumerating objects: 2252, done.
remote: Counting objects: 100% (870/870), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 2252 (delta 844), reused 823 (delta 817), pack-reused 1382
Receiving objects: 100% (2252/2252), 5.92 MiB | 3.64 MiB/s, done.
Resolving deltas: 100% (1692/1692), completed with 42 local objects.
From https://github.com/sairish2001/MakesMathEasy
 * branch            main       -> FETCH_HEAD
   ba6a93e..9f1b515  main       -> upstream/main

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$ git reset --hard upstream/main
Updating files: 100% (129/129), done.
HEAD is now at 9f1b515 added subtraction of decimal no.s using 10's complement (#1510)

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (main)
$ git checkout factors
Switched to branch 'factors'

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git status
On branch factors
nothing to commit, working tree clean

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git log
commit ad3714badcbac81c29a342f6cdf1010a887327f5 (HEAD -> factors, origin/factors)
Author: keshavgbpecdelhi <keshavraturi333@gmail.com>
Date:   Thu Mar 25 12:49:04 2021 +0530

    Fixed everything realated to Factors/LCM/HCF in General Maths Section

commit 4f2ba60853aca068c1e4493ef6ba71ac02713218
Author: keshavgbpecdelhi <keshavraturi333@gmail.com>
Date:   Mon Mar 22 12:24:12 2021 +0530

    fixed factors

commit 23ee90a1d755befa48b9bbe47e809ad07f884475 (origin/main, origin/HEAD)
Author: Kanishka Vijayvargiya <kanishkav8jan@gmail.com>
Date:   Thu Mar 18 16:53:58 2021 +0530

    Added warning in matrix calculator when negative value is entered in dimension (#237)

commit 23c0625d58a3846d84e4170dc292b568c2eafd96
Author: Satyam Singh <56315878+satcasm@users.noreply.github.com>
Date:   Thu Mar 18 10:03:10 2021 +0530

    Fixed inline styling (#234)

    * added product-to-sum/sum-to-product identities

    * added complex calculations

    * improved the inline styling and changed pxs to rems

    * improved upon comment lines

    * final changes

    Co-authored-by: Rajinderpal Singh <60106112+sairish2001@users.noreply.github.com>

commit e5644fdbedf9de73513b3e5a2a35c762ca96e439
Author: anjali7786 <57794837+anjali7786@users.noreply.github.com>

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git rebase main
First, rewinding head to replay your work on top of it...
Applying: fixed factors
.git/rebase-apply/patch:39: trailing whitespace.
      if(num!=i)
.git/rebase-apply/patch:67: trailing whitespace.
        if(num!=i)
warning: 2 lines add whitespace errors.
Using index info to reconstruct a base tree...
M       README.md
M       appjs/logicjavascript.js
Falling back to patching base and 3-way merge...
Auto-merging appjs/logicjavascript.js
CONFLICT (content): Merge conflict in appjs/logicjavascript.js
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 fixed factors
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors|REBASE 1/2)
$ code appjs/logicjavascript.js

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors|REBASE 1/2)
$ git rebase --abort

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git reset --soft Head~1

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git commit --ammend
error: unknown option `ammend'
usage: git commit [<options>] [--] <pathspec>...

    -q, --quiet           suppress summary after successful commit
    -v, --verbose         show diff in commit message template

Commit message options
    -F, --file <file>     read message from file
    --author <author>     override author for commit
    --date <date>         override date for commit
    -m, --message <message>
                          commit message
    -c, --reedit-message <commit>
                          reuse and edit message from specified commit
    -C, --reuse-message <commit>
                          reuse message from specified commit
    --fixup <commit>      use autosquash formatted message to fixup specified commit
    --squash <commit>     use autosquash formatted message to squash specified commit
    --reset-author        the commit is authored by me now (used with -C/-c/--amend)
    -s, --signoff         add Signed-off-by:
    -t, --template <file>
                          use specified template file
    -e, --edit            force edit of commit
    --cleanup <mode>      how to strip spaces and #comments from message
    --status              include status in commit message template
    -S, --gpg-sign[=<key-id>]
                          GPG sign commit

Commit contents options
    -a, --all             commit all changed files
    -i, --include         add specified files to index for commit
    --interactive         interactively add files
    -p, --patch           interactively add changes
    -o, --only            commit only specified files
    -n, --no-verify       bypass pre-commit and commit-msg hooks
    --dry-run             show what would be committed
    --short               show status concisely
    --branch              show branch information
    --ahead-behind        compute full ahead/behind values
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    --amend               amend previous commit
    --no-post-rewrite     bypass post-rewrite hook
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)


Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git commit --amend
[factors 9cb374c] fixed factors
 Date: Mon Mar 22 12:24:12 2021 +0530
 5 files changed, 76 insertions(+), 5 deletions(-)

Keshav Raturi@DESKTOP-KEALHUA MINGW64 ~/Desktop/MakesMathEasy/MakesMathEasy (factors)
$ git log
commit 9cb374ce6cd4ca51bb90935a78edc042cd2c48bb (HEAD -> factors)
Author: keshavgbpecdelhi <keshavraturi333@gmail.com>
Date:   Mon Mar 22 12:24:12 2021 +0530

    fixed factors

 [...]

2021-04-30 04:30 UTC, sairish2001 requested changes
This PR is showing alot of Deletions. Have a look. Till then you can move on to any other issue, if you want to work on.

2021-04-30 04:33 UTC, sairish2001 commented
And also this issue is already resolved by someone

2021-04-30 15:13 UTC, closed without merging